insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (1, 56, 1, 'Inspection', '3988 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (2, 57, 1, 'Overcrowded', '2767 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (3, 58, 1, 'Overcrowded', '1939 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (4, 59, 1, 'Unloading', '3550 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (5, 60, 1, 'Available', '2574 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (6, 61, 1, 'Under Maintenance', '3205 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (7, 62, 1, 'Inspection', '3633 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (8, 63, 1, 'Emergency Use', '1504 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (9, 64, 1, 'Inspection', '3678 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (10, 65, 1, 'Closed', '3635 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (11, 66, 1, 'Reserved', '2136 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (12, 67, 1, 'Available', '2237 million', 'Los Angeles, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (13, 68, 2, 'Overcrowded', '4608 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (14, 69, 2, 'Inspection', '4441 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (15, 70, 2, 'Overcrowded', '4065 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (16, 71, 2, 'Emergency Use', '2773 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (17, 72, 2, 'Available', '3840 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (18, 73, 2, 'Unloading', '2403 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (19, 74, 2, 'Overcrowded', '2479 million', 'Long Beach, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (20, 75, 3, 'Idle', '3332 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (21, 76, 3, 'Closed', '4785 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (22, 77, 3, 'Inspection', '3123 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (23, 78, 3, 'Idle', '3826 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (24, 79, 3, 'Available', '1725 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (25, 80, 3, 'Occupied', '2067 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (26, 81, 3, 'Overcrowded', '3526 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (27, 82, 3, 'Closed', '4554 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (28, 83, 3, 'Available', '3015 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (29, 84, 3, 'Available', '3289 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (30, 85, 3, 'Occupied', '1453 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (31, 86, 3, 'Loading', '1120 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (32, 87, 3, 'Under Maintenance', '2904 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (33, 88, 3, 'Closed', '4314 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (34, 89, 3, 'Overcrowded', '2276 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (35, 90, 3, 'Loading', '3783 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (36, 91, 3, 'Occupied', '1570 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (37, 92, 3, 'Unloading', '3690 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (38, 93, 3, 'Unloading', '3798 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (39, 94, 3, 'Emergency Use', '2641 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (40, 95, 3, 'Available', '1248 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (41, 96, 3, 'Available', '4236 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (42, 97, 3, 'Reserved', '4826 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (43, 98, 3, 'Available', '4969 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (44, 99, 3, 'Emergency Use', '2384 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (45, 100, 4, 'Inspection', '1820 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (46, 101, 4, 'Unloading', '1926 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (47, 102, 4, 'Available', '2687 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (48, 103, 4, 'Loading', '2018 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (49, 104, 4, 'Closed', '1583 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (50, 105, 4, 'Unloading', '2236 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (51, 106, 4, 'Inspection', '1396 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (52, 107, 4, 'Loading', '3863 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (53, 108, 4, 'Inspection', '2012 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (54, 109, 4, 'Emergency Use', '2066 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (55, 110, 4, 'Available', '2069 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (56, 111, 4, 'Loading', '2058 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (57, 112, 4, 'Under Maintenance', '4617 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (58, 113, 4, 'Loading', '1151 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (59, 114, 4, 'Inspection', '2429 million', 'Savannah, GA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (60, 115, 5, 'Loading', '2583 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (61, 116, 5, 'Idle', '3015 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (62, 117, 5, 'Emergency Use', '4667 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (63, 118, 5, 'Emergency Use', '1967 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (64, 119, 5, 'Overcrowded', '3355 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (65, 120, 5, 'Inspection', '4294 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (66, 121, 5, 'Available', '4969 million', 'Houston, TX');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (67, 122, 6, 'Inspection', '1871 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (68, 123, 6, 'Under Maintenance', '3344 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (69, 124, 6, 'Unloading', '4209 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (70, 125, 6, 'Under Maintenance', '3583 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (71, 126, 6, 'Reserved', '1471 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (72, 127, 6, 'Idle', '2746 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (73, 128, 6, 'Overcrowded', '1242 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (74, 129, 6, 'Overcrowded', '4879 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (75, 130, 6, 'Inspection', '2043 million', 'Charleston, SC');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (76, 131, 7, 'Occupied', '2136 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (77, 132, 7, 'Loading', '4441 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (78, 133, 7, 'Available', '2384 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (79, 134, 7, 'Reserved', '4160 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (80, 135, 7, 'Unloading', '3731 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (81, 136, 7, 'Overcrowded', '2233 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (82, 137, 7, 'Overcrowded', '1945 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (83, 138, 7, 'Inspection', '2829 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (84, 139, 7, 'Inspection', '4530 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (85, 140, 7, 'Occupied', '1292 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (86, 141, 7, 'Idle', '4304 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (87, 142, 7, 'Overcrowded', '4933 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (88, 143, 7, 'Unloading', '4785 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (89, 144, 7, 'Idle', '3189 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (90, 145, 7, 'Available', '1402 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (91, 146, 7, 'Available', '4933 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (92, 147, 7, 'Available', '4053 million', 'Oakland, CA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (93, 148, 8, 'Under Maintenance', '2069 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (94, 149, 8, 'Idle', '2999 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (95, 150, 8, 'Occupied', '1717 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (96, 151, 8, 'Idle', '2236 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (97, 152, 8, 'Inspection', '4431 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (98, 153, 8, 'Closed', '1720 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (99, 154, 8, 'Under Maintenance', '1151 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (100, 155, 8, 'Closed', '4879 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (101, 156, 8, 'Available', '1720 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (102, 157, 8, 'Unloading', '3921 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (103, 158, 8, 'Available', '4772 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (104, 159, 8, 'Idle', '4431 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (105, 160, 8, 'Unloading', '4128 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (106, 161, 8, 'Occupied', '1874 million', 'Seattle-Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (107, 162, 9, 'Available', '2602 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (108, 163, 9, 'Unloading', '3693 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (109, 164, 9, 'Inspection', '1330 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (110, 165, 9, 'Unloading', '3979 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (111, 166, 9, 'Occupied', '2370 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (112, 167, 9, 'Unloading', '2495 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (113, 168, 9, 'Under Maintenance', '1517 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (114, 169, 9, 'Idle', '1336 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (115, 170, 9, 'Unloading', '3199 million', 'Miami, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (116, 171, 10, 'Idle', '1720 million', 'Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (117, 172, 10, 'Closed', '2384 million', 'Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (118, 173, 10, 'Loading', '3372 million', 'Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (119, 174, 10, 'Idle', '2829 million', 'Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (120, 175, 10, 'Inspection', '2204 million', 'Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (121, 176, 10, 'Loading', '4209 million', 'Tacoma, WA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (122, 177, 11, 'Reserved', '3292 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (123, 178, 11, 'Available', '3529 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (124, 179, 11, 'Closed', '2384 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (125, 180, 11, 'Occupied', '1099 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (126, 181, 11, 'Reserved', '4240 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (127, 182, 11, 'Closed', '3327 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (128, 183, 11, 'Inspection', '4441 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (129, 184, 11, 'Available', '3578 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (130, 185, 11, 'Loading', '2067 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (131, 186, 11, 'Inspection', '3864 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (132, 187, 11, 'Available', '1940 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (133, 188, 11, 'Under Maintenance', '4355 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (134, 189, 11, 'Emergency Use', '3903 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (135, 190, 11, 'Occupied', '3065 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (136, 191, 11, 'Inspection', '4343 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (137, 192, 11, 'Loading', '2906 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (138, 193, 11, 'Under Maintenance', '3447 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (139, 194, 11, 'Unloading', '2484 million', 'Boston, MA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (140, 195, 12, 'Closed', '2767 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (141, 196, 12, 'Idle', '1237 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (142, 197, 12, 'Reserved', '2370 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (143, 198, 12, 'Under Maintenance', '4439 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (144, 199, 12, 'Under Maintenance', '2429 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (145, 200, 12, 'Reserved', '1740 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (146, 201, 12, 'Available', '2384 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (147, 202, 12, 'Emergency Use', '1764 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (148, 203, 12, 'Inspection', '1974 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (149, 204, 12, 'Under Maintenance', '3578 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (150, 205, 12, 'Occupied', '1878 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (151, 206, 12, 'Idle', '4149 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (152, 207, 12, 'Closed', '2721 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (153, 208, 12, 'Loading', '1627 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (154, 209, 12, 'Reserved', '1162 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (155, 210, 12, 'Closed', '3529 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (156, 211, 12, 'Available', '2976 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (157, 212, 12, 'Reserved', '1434 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (158, 213, 12, 'Overcrowded', '2933 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (159, 214, 12, 'Overcrowded', '3065 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (160, 215, 12, 'Occupied', '1261 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (161, 216, 12, 'Under Maintenance', '3800 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (162, 217, 12, 'Unloading', '2066 million', 'New Orleans, LA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (163, 218, 13, 'Emergency Use', '2024 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (164, 219, 13, 'Loading', '4969 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (165, 220, 13, 'Unloading', '2069 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (166, 221, 13, 'Reserved', '3015 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (167, 222, 13, 'Available', '1799 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (168, 223, 13, 'Reserved', '3578 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (169, 224, 13, 'Loading', '2641 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (170, 225, 13, 'Idle', '3289 million', 'Jacksonville, FL');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (171, 226, 14, 'Under Maintenance', '4128 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (172, 227, 14, 'Loading', '2976 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (173, 228, 14, 'Occupied', '3939 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (174, 229, 14, 'Emergency Use', '3289 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (175, 230, 14, 'Inspection', '1583 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (176, 231, 14, 'Idle', '1299 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (177, 232, 14, 'Overcrowded', '1820 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (178, 233, 14, 'Loading', '4879 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (179, 234, 14, 'Under Maintenance', '4803 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (180, 235, 14, 'Unloading', '1718 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (181, 236, 14, 'Loading', '1788 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (182, 237, 14, 'Occupied', '2370 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (183, 238, 14, 'Overcrowded', '1261 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (184, 239, 14, 'Closed', '2024 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (185, 240, 14, 'Under Maintenance', '1871 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (186, 241, 14, 'Occupied', '3065 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (187, 242, 14, 'Idle', '2266 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (188, 243, 14, 'Idle', '1120 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (189, 244, 14, 'Occupied', '2970 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (190, 245, 14, 'Idle', '1681 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (191, 246, 14, 'Unloading', '3226 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (192, 247, 14, 'Reserved', '4043 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (193, 248, 14, 'Closed', '1663 million', 'Philadelphia, PA');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (194, 249, 15, 'Loading', '2366 million', 'Baltimore, MD');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (195, 250, 15, 'Overcrowded', '4642 million', 'Baltimore, MD');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (196, 251, 15, 'Emergency Use', '1392 million', 'Baltimore, MD');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (197, 252, 15, 'Emergency Use', '3327 million', 'Baltimore, MD');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (198, 253, 15, 'Overcrowded', '4695 million', 'Baltimore, MD');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (199, 254, 15, 'Under Maintenance', '4065 million', 'Baltimore, MD');
insert into portmanagement.dock (DockID, DockManagerID, PortID, Status, Capacity, Location) values (200, 255, 15, 'Under Maintenance', '3787 million', 'Baltimore, MD');
