insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (1, 16, 1, 'Empty', '86726 million', 'Los Angeles, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (2, 17, 1, 'Under Maintenance', '91522 million', 'Los Angeles, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (3, 18, 1, 'Reserved', '86601 million', 'Los Angeles, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (4, 19, 2, 'Closed', '75280 million', 'Long Beach, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (5, 20, 2, 'Closed', '59178 million', 'Long Beach, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (6, 21, 2, 'Reserved', '52043 million', 'Long Beach, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (7, 22, 3, 'Expanding', '32644 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (8, 23, 3, 'Empty', '26433 million', 'New York and New Jersey, NY/NJ');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (9, 24, 4, 'Closed', '39004 million', 'Savannah, GA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (10, 25, 4, 'Reserved', '35982 million', 'Savannah, GA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (11, 26, 5, 'Waiting for Shipment', '52634 million', 'Houston, TX');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (12, 27, 5, 'Processing', '69151 million', 'Houston, TX');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (13, 28, 5, 'Waiting for Shipment', '65424 million', 'Houston, TX');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (14, 29, 5, 'Active', '47392 million', 'Houston, TX');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (15, 30, 6, 'Expanding', '15197 million', 'Charleston, SC');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (16, 31, 6, 'Processing', '24722 million', 'Charleston, SC');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (17, 32, 6, 'Inactive', '69391 million', 'Charleston, SC');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (18, 33, 6, 'Inactive', '69301 million', 'Charleston, SC');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (19, 34, 6, 'Active', '94208 million', 'Charleston, SC');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (20, 35, 7, 'Empty', '24553 million', 'Oakland, CA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (21, 36, 8, 'Processing', '92092 million', 'Seattle-Tacoma, WA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (22, 37, 9, 'Under Maintenance', '87777 million', 'Miami, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (23, 38, 9, 'Reserved', '89167 million', 'Miami, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (24, 39, 9, 'Expanding', '86601 million', 'Miami, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (25, 40, 9, 'Inactive', '16486 million', 'Miami, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (26, 41, 9, 'Empty', '54293 million', 'Miami, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (27, 42, 10, 'Under Maintenance', '61353 million', 'Tacoma, WA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (28, 43, 11, 'Reserved', '19603 million', 'Boston, MA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (29, 44, 11, 'Empty', '69344 million', 'Boston, MA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (30, 45, 12, 'Expanding', '40175 million', 'New Orleans, LA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (31, 46, 13, 'Full', '62950 million', 'Jacksonville, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (32, 47, 13, 'Processing', '97433 million', 'Jacksonville, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (33, 48, 13, 'Processing', '32644 million', 'Jacksonville, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (34, 49, 13, 'Under Maintenance', '12654 million', 'Jacksonville, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (35, 50, 13, 'Processing', '87777 million', 'Jacksonville, FL');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (36, 51, 14, 'Closed', '28306 million', 'Philadelphia, PA');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (37, 52, 15, 'Full', '36649 million', 'Baltimore, MD');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (38, 53, 15, 'Expanding', '69344 million', 'Baltimore, MD');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (39, 54, 15, 'Active', '78377 million', 'Baltimore, MD');
insert into portmanagement.warehouse (WarehouseID, WarehouseManagerID, PortID, Status, Capacity, Location) values (40, 55, 15, 'Reserved', '62950 million', 'Baltimore, MD');
